### ISSUE TITLE
MTE和LightingBox2插件冲突了

### ISSUE THREAD

**Issue by DFVSQY** [zwcloud/MeshTerrainEditor-issues#11]
**Environment**  
 - OS: Win7 x64
 - Unity version: 5.6.5f1
 - MTE Version: 3.2.0

使用MTE进行地形转网格操作，在没有导入LightBox应用到场景中时导出的地形网格表现效果和原来地形基本符合，但是应用了LightBox后地形网格的表现效果完全不正确了：
![image](https://user-images.githubusercontent.com/8075421/41826157-eca78534-7859-11e8-94e5-8c6425e917e3.png)
地形网格中拥有了大量的黑乎乎的区域，经测试好像与最后一个贴图控制有关：
![image](https://user-images.githubusercontent.com/8075421/41826192-300f2e08-785a-11e8-9d6f-b59b23ba363f.png)
@zwcloud 这个究竟是什么原因造成的？如何修改？急用，多谢。

**Comment by DFVSQY** [comment]
除去建筑后整个地形网格的预览图：

**Comment by zwcloud** [comment]
这个问题与之前客户反馈过的问题很相似：
https://forum.unity.com/threads/mte.396808/page-5#post-3210536

还有一位用户也反馈过：
![image](https://user-images.githubusercontent.com/6965758/41832046-dad86b98-787c-11e8-8b67-8f6c442851d2.png)

*正确的解决方法*是：
修改Control贴图的导入设置为 不选中“sRGB (Color Texture)”
![image](https://user-images.githubusercontent.com/6965758/41832122-335989fa-787d-11e8-9aa7-9496f8f4aa98.png)

在Unity 5.6.5f1 和 2017.3.0f3 上测试可行。

**Comment by zwcloud** [comment]
@DFVSQY 
> 为何把分割数限制为16？

这个是当时开发MTE原型版本时，参考了T4M的转换器的限制，我记得T4M的转换器最低是32.

对于平面而言，确实可以减少这个限制，以后的版本会更改为2，您觉得如何？

**Comment by DFVSQY** [comment]
@zwcloud 能尽可能灵活配置最好了，最好XY方向上都能自定义分割数量 因为有的地形是长方形的

**Comment by zwcloud** [comment]
@DFVSQY 
可以的。另外，长方形的地形还没有做过测试，不确定现在MTE是否支持对其进行编辑。
