### ISSUE TITLE
Can't use pro features on pro version error

### ISSUE THREAD

**Issue by LuminousSilver** [zwcloud/MeshTerrainEditor-issues#12]
When I try to change my splat count to 2 (only need 2 textures) it errors with: "Using splat textures except 4 is a pro-only feature." I bought the pro version and the buy button links back to unity store and shows import option on it.

I am on Unity Version 2018.1.6f1

**Comment by zwcloud** [comment]
Have you activated MTE Pro? Please follow the instructions in the MTE_ReadMe.htm to activate MTE Pro first with the invoice number of your purchase.
