### ISSUE TITLE
为什么地形纹理最多只支持5张？现在地形有8张甚至10张的这部分如何处理？

### ISSUE THREAD

**Issue by DFVSQY** [zwcloud/MeshTerrainEditor-issues#15]
如题，地形纹理超过5张的支持究竟会产生什么问题？如果拥有更多地形纹理如何处理？

**Comment by zwcloud** [comment]
你好，可以通过平铺的方式使用多于5张贴图，请参考ReadMe中的**常问问题11：MTE可以使用多于5张贴图吗？**。

每个单块模型上只能使用5张，这是因为MTE坚持使用一个pass的渲染，即一个mesh只占用一次drawcall. 
 Unity地形的多于4张贴图的地形都是多pass渲染，因而渲染效率较低。

**Comment by DFVSQY** [comment]
多谢，平铺是个好方法。
