### ISSUE TITLE
Converting a terrain to MTE preserving lightmaps results in lightmap disappearing as soon as it enters playmode

### ISSUE THREAD

**Issue by manliogreco** [zwcloud/MeshTerrainEditor-issues#209]
Converting a terrain to MTE preserving lightmaps results in lightmap disappearing as soon as it enters playmode.

The converted object is reverted to a non-lightmapped one, actually losing its lightmap reference

**Comment by zwcloud** [comment]
I see. I'll try to reproduce the issue today.

**Comment by zwcloud** [comment]
I have reproduced the issue and looking into it.

**Comment by manliogreco** [comment]
Great!

Il sab 18 set 2021, 14:56 Zou Wei ***@***.***> ha scritto:

**Comment by zwcloud** [comment]
Fixed at https://github.com/zwcloud/MeshTerrainEditor/commit/998849091d0585b279efa5d3109f422a41bbedbf
