### ISSUE TITLE
Null Meshes with Unity 2018.2.6f1

### ISSUE THREAD

**Issue by salvobunetto** [zwcloud/MeshTerrainEditor-issues#23]
When I create or convert a terrain at the end of the process I find an error and an empty mesh (200KB)

this is the error:

> ImportFBX
> 
>  Errors:
> Couldn't import file C:/Users/Salvo/Documents/Unity 5/Online/Assets/Scenes/NewMeshTerrain2/NewMeshTerrain2.obj.
> 
> 0x0000000141535E48 (Unity) StackWalker::GetCurrentCallstack
> 0x000000014153C386 (Unity) StackWalker::ShowCallstack
> 0x000000014140B59B (Unity) GetStacktrace
> 0x00000001408AF9C0 (Unity) DebugStringToFile
> 0x0000000140116121 (Unity) DebugStringToFile<core::basic_string<char,core::StringStorageDefault<char> > >
> 0x0000000141FF06D3 (Unity) AssetDatabaseV1::UpdateAsset
> 0x0000000141FE3C02 (Unity) AssetInterface::ProcessAssetsImplementation
> 0x0000000141FEDB2A (Unity) AssetInterface::StopAssetEditing
> 0x0000000141FDF4F3 (Unity) AssetInterface::ImportAtPath
> 0x0000000141F9AA57 (Unity) AssetDatabase::ImportAtPath
> 0x0000000141551C82 (Unity) AssetDatabase_CUSTOM_ImportAsset
> 0x0000000035899C67 (Mono JIT Code) (wrapper managed-to-native) UnityEditor.AssetDatabase:ImportAsset (string,UnityEditor.ImportAssetOptions)
> 0x000000003589C423 (Mono JIT Code) [AssetDatabaseBindings.gen.cs:166] UnityEditor.AssetDatabase:ImportAsset (string) 
> 0x000000003589C30B (Mono JIT Code) [AssetImporter.bindings.cs:96] UnityEditor.AssetImporter:SaveAndReimport () 
> 0x00000000358942A3 (Mono JIT Code) ‍⁮⁫‬‏‏‌‮⁬⁯⁭‬‍‎⁭⁫‮⁪‎​‍⁭⁬‭⁯‪‬⁪​⁭‌​‭​‏‏‮⁮​‪‮:⁭‌‮‌‏​‬⁪‌⁬⁫‎⁬‫‏⁮‏⁪⁯‍⁪‮‬​‏‎⁮‍⁯⁯⁬‪⁭‌⁯​​‮‎‍‮ ()
> 0x0000000035630CFB (Mono JIT Code) ‍⁮⁫‬‏‏‌‮⁬⁯⁭‬‍‎⁭⁫‮⁪‎​‍⁭⁬‭⁯‪‬⁪​⁭‌​‭​‏‏‮⁮​‪‮:OnGUI ()
> 0x0000000031048D70 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
> 0x00007FFC4B19A5EB (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
> 0x00007FFC4B121B02 (mono-2.0-bdwgc) [object.c:2915] do_runtime_invoke 
> 0x00007FFC4B12ACC2 (mono-2.0-bdwgc) [object.c:3067] mono_runtime_invoke_checked 
> 0x00007FFC4B12B459 (mono-2.0-bdwgc) [object.c:5253] mono_runtime_try_invoke_array 
> 0x00007FFC4B12AC56 (mono-2.0-bdwgc) [object.c:5131] mono_runtime_invoke_array_checked 
> 0x00007FFC4B0CFD64 (mono-2.0-bdwgc) [icall.c:3357] ves_icall_InternalInvoke 
> 0x000000002DB8F1D6 (Mono JIT Code) (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
> 0x000000002DB8D04B (Mono JIT Code) System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
> 0x000000002DB8CD0F (Mono JIT Code) System.Reflection.MethodBase:Invoke (object,object[])
> 0x000000002FE49B13 (Mono JIT Code) [HostView.cs:295] UnityEditor.HostView:Invoke (string,object) 
> 0x000000002FE49963 (Mono JIT Code) [HostView.cs:289] UnityEditor.HostView:Invoke (string) 
> 0x000000003561D053 (Mono JIT Code) [HostView.cs:105] UnityEditor.HostView:OldOnGUI () 
> 0x00000000313191D4 (Mono JIT Code) [IMGUIContainer.cs:216] UnityEngine.Experimental.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,bool) 
> 0x0000000031317803 (Mono JIT Code) [IMGUIContainer.cs:378] UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event) 
> 0x000000002FE42C6B (Mono JIT Code) [IMGUIContainer.cs:355] UnityEngine.Experimental.UIElements.IMGUIContainer:HandleEvent (UnityEngine.Experimental.UIElements.EventBase) 
> 0x000000002F617684 (Mono JIT Code) [EventDispatcher.cs:265] UnityEngine.Experimental.UIElements.EventDispatcher:DispatchEvent (UnityEngine.Experimental.UIElements.EventBase,UnityEngine.Experimental.UIElements.IPanel) 
> 0x0000000010C3B24B (Mono JIT Code) [UIElementsUtility.cs:244] UnityEngine.Experimental.UIElements.UIElementsUtility:DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel) 
> 0x0000000010C3AABB (Mono JIT Code) [UIElementsUtility.cs:74] UnityEngine.Experimental.UIElements.UIElementsUtility:ProcessEvent (int,intptr) 
> 0x0000000010C3A424 (Mono JIT Code) [GUIUtility.cs:171] UnityEngine.GUIUtility:ProcessEvent (int,intptr) 
> 0x0000000010C3A643 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool_int_intptr (object,intptr,intptr,intptr)
> 0x00007FFC4B19A5EB (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
> 0x00007FFC4B121B02 (mono-2.0-bdwgc) [object.c:2915] do_runtime_invoke 
> 0x00007FFC4B12AAEF (mono-2.0-bdwgc) [object.c:2962] mono_runtime_invoke 
> 0x0000000140C053AA (Unity) scripting_method_invoke
> 0x0000000140BFD5C0 (Unity) ScriptingInvocation::Invoke
> 0x0000000140BF867A (Unity) ScriptingInvocation::Invoke<bool>
> 0x00000001404172C9 (Unity) IMGUIScriptingClasses::ProcessEvent
> 0x0000000141397B04 (Unity) GUIView::ProcessRetainedMode
> 0x00000001415CDFD2 (Unity) GUIView::OnInputEvent
> 0x0000000141397A8C (Unity) GUIView::ProcessInputEvent
> 0x00000001415CF32A (Unity) GUIView::ProcessEventMessages
> 0x00000001415C8A5D (Unity) GUIView::GUIViewWndProc
> 0x00007FFC74186CC1 (USER32) CallWindowProcW
> 0x00007FFC74186693 (USER32) DispatchMessageW
> 0x00000001415E7E14 (Unity) MainMessageLoop
> 0x00000001415EA038 (Unity) WinMain
> 0x000000014242E5AA (Unity) __scrt_common_main_seh
> 0x00007FFC74BA3034 (KERNEL32) BaseThreadInitThunk
> 0x00007FFC76B11461 (ntdll) RtlUserThreadStart

**Comment by zwcloud** [comment]
Thanks for the feedback.
Could you upload the obj file, please? I will check if it is really corrupted. The error seems caused by the internal fbx importer of Unity. I will also try to reproduce the issue.

**Comment by salvobunetto** [comment]
> Thanks for the feedback.
> Could you upload the obj file and the screenshot of the error, please? I will check if it is really corrupted. The error seems caused by the internal fbx importer of Unity. I will also try to reproduce the issue.

PS. I tried other versions, re-imported the whole project but the problem persists

![error](https://user-images.githubusercontent.com/29382220/45755442-bd8d6080-bc1e-11e8-8ff0-bff4c64f18f5.JPG)

Full error is on first post

Zip of a new "blank" mesh terrain [NewMeshTerrain.zip](https://github.com/zwcloud/MeshTerrainEditor-issues/files/2397154/NewMeshTerrain.zip)

**Comment by zwcloud** [comment]
> Zip of a new "blank" mesh terrain NewMeshTerrain.zip

Just tested with Unity 2018.2.8f1 and Unity reports that it failed to import it.
![image](https://user-images.githubusercontent.com/6965758/45756246-019a5880-bc53-11e8-8686-e00aeee9ec85.png)

The obj file is weird: all dot(`.`) in it is replaced with a comma(`,`). Are you sure this obj is created by MTE Creator?

**Comment by salvobunetto** [comment]
Might help you know that i have the photon plugin

**Comment by salvobunetto** [comment]
With a text editor I replaced all (,) with I (.) and the file was read
correctly, but as you see from the video I sent you mte I create this
incongruity, how can i solve?
I have not yet tried to edit a plot (this problem may recur in the save of
the mesh)

Il giorno mer 19 set 2018 alle ore 16:01 <salvobunetto@gmail.com> ha
scritto:

**Comment by zwcloud** [comment]
> but as you see from the video I sent you mte I create this incongruity

Sorry, I didn't see a video. Maybe a Github reply email doesn't support attachment.

> I have not yet tried to edit a plot (this problem may recur in the save of the mesh)

Try using MTE in an empty project. If it works, then it is some other plugins, probably photon, that keeps changing the obj file into an incongruous one.

To walkaround this problem, you can use `.asset` as the file format instead of `.obj`. I think photon will not modify `.asset` files.

**Comment by salvobunetto** [comment]
Thanks, the. Asset File Works

Il giorno mer 19 set 2018 alle ore 16:33 Zou Wei <notifications@github.com>
ha scritto:
